### ISSUE TITLE
Adding of Quotes from films other than Infinity Wars

### ISSUE THREAD

**Issue by nzec** [sggts04/thanosapi#2]
Is this repository for quotes from **Avengers : Infinity Wars** only?
Or should we add quotes from comics and other films as well?

**Comment by sggts04** [comment]
It has to be a quote by Thanos from the movies not comics. Any movie, but before Infinity War we've only had 1 or 2 by him which I think I have included here. Feel free to send a PR if I've missed any from the movies, and you could also PR after Endgame release, although I might take some time to accept that pull request since I don't want any spoilers xD
