### ISSUE TITLE
NPM package?

### ISSUE THREAD

**Issue by SirObby** [sggts04/thanosapi#7]
How would i use this in NodeJS?
Is there like a NPM package or a code snippet?

**Comment by SirObby** [comment]
I just asked this in a SpeakJS discord server.
So might just post answer here.

**Comment by sggts04** [comment]
@SirObby 
Its just a normal API that you can send an HTTP request to, not an NPM package.

For example, for NodeJS you can just use an HTTP request package like `axios` to send a get request and fetch the data. Example Code:
```js
const axios = require('axios');

axios.get("https://thanosapi.herokuapp.com/random/")
        .then(response => {
                        console.log(response.data);
        })
```

**Comment by SirObby** [comment]
Actually it dosent work for some reason.
https://i.imgur.com/ncetngT.png (yes i used response.data)

**Comment by SirObby** [comment]
https://i.imgur.com/5zy8sbJ.png

**Comment by SirObby** [comment]
Nevermind fixed it..

**Comment by sggts04** [comment]
Because response.data is an object which contains data in the variables `id` and `quote`.  This is what response.data returns: https://thanosapi.herokuapp.com/random/

You have to unpack it yourself. Come on, you could have atleast done a console.log to see what it returns before directly sending into discord. I'm not opening this issue again.

**Comment by SirObby** [comment]
I just fixed it...
